cambios en clases vino reseña tipo vino
FrancoDiazLuna/BomvinoApp pull request #2
Opened 2024-05-23 16:35 UTC by ZoiLyp

2024-05-23 16:37 UTC, EzePCba commented on BonvinoApp/CapaNegocio/Vino.cs
> +                { //string nombreBodega = Bodega.Nombre;
Borrar código comentado

2024-05-23 16:42 UTC, ZoiLyp commented on BonvinoApp/CapaNegocio/Vino.cs
> +                { //string nombreBodega = Bodega.Nombre;
listo

2024-05-23 21:26 UTC, FrancoDiazLuna commented on BonvinoApp/CapaNegocio/Reseña.cs
Para que esto no falle hay que validar:
-  que cuando se haga una instancia de Reseña se le asigne un valor valido y != null a FechaReseña
- que la fechaDesde no sea posterior a fechaHasta, que se supone lo validamos en la pantalla

2024-05-23 21:49 UTC, FrancoDiazLuna requested changes

2024-05-23 21:49 UTC, FrancoDiazLuna commented on BonvinoApp/CapaNegocio/Reseña.cs
sosDeSommelier() no resuelve correctamente el requerimiento de validar si la Reseña es de un Sommelier o de un Enófilo, hay que resolver esto en los diagramas.
Ademas de que TipoReseña no existe.

Esto hay que analizar mejor en el diagrama y con el tema de las relaciones

2024-05-23 21:49 UTC, FrancoDiazLuna commented on BonvinoApp/CapaNegocio/Vino.cs
el campo private List<Reseña> reseñas; debe admitir nulos, ya que el Vino puede o no tener reseñas, debido a la multiplicidad descripta en el diagrama 0...* (cero a muchas)

2024-05-23 21:49 UTC, FrancoDiazLuna commented on BonvinoApp/CapaNegocio/Reseña.cs
Hay que agregar el atributo `private Vino vino;` ya que según el diagrama, cuando se crea una Reseña esta debe estar relacionada a un (1) Vino

2024-05-23 21:49 UTC, FrancoDiazLuna commented on BonvinoApp/CapaNegocio/Vino.cs
los métodos se nombran con la primer letra en minúscula:
- TenesReseñasDeTipoEnPeriodo() -> tenesReseñasDeTipoEnPeriodo
- BuscarInfoBodega() -> buscarInfoBodega()
- BuscarVarietal() -> buscarVarietal()
- CalcularPjeDeSommelierEnPeriodo() -> calcularPjeDeSommelierEnPeriodo()

los métodos get y/o set deben ir en su región correspondiente, y de igual formato al de los demás atributos de la clase para mantener una consistencia en la forma que escribimos código.

2024-05-23 21:49 UTC, FrancoDiazLuna commented on BonvinoApp/CapaNegocio/Vino.cs
el método buscarInfoBodega() tiene un comportamiento no esperado, ya que el Vino conoce a su bodega, lo tiene como un atributo referenciado, definido por la relación entre ambas clases. No es correcta la implementación

2024-05-23 21:49 UTC, FrancoDiazLuna commented on BonvinoApp/obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache
esto no debe modificarse ni subirse!
y se modifica es solo en local

2024-05-23 21:49 UTC, FrancoDiazLuna commented on BonvinoApp/obj/Debug/BonvinoApp.csproj.FileListAbsolute.txt
esto no debe modificarse ni subirse!
y se modifica es solo en local

2024-05-23 21:49 UTC, FrancoDiazLuna commented on BonvinoApp/obj/Debug/.NETFramework,Version=v4.8.AssemblyAttributes.cs
esto no debe modificarse ni subirse!
y se modifica es solo en local

2024-05-24 01:09 UTC, ZoiLyp commented on BonvinoApp/CapaNegocio/Vino.cs
cuando decis esto: 
los métodos get y/o set deben ir en su región correspondiente, y de igual formato al de los demás atributos de la clase para mantener una consistencia en la forma que escribimos código. 
te referis a los metodos que tengo de get nombre get precio?

2024-05-24 01:12 UTC, ZoiLyp commented on BonvinoApp/CapaNegocio/Vino.cs
> el campo private List<Reseña> reseñas; debe admitir nulos, ya que el Vino puede o no tener reseñas, debido a la multiplicidad descripta en el diagrama 0...* (cero a muchas)

esto se deberia hacer asi? 
#region [Atributos]
private List<Reseña?> reseñas;

2024-05-25 17:36 UTC, closed without merging